// <auto-generated />
using System;
using Dive_Deep.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dive_Deep.Migrations
{
    [DbContext(typeof(DiveDeepContext))]
    partial class DiveDeepContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dive_Deep.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("BookingId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Dive_Deep.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PricePerDay")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Dive_Deep.Models.ProductBooking", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "BookingId");

                    b.HasIndex("BookingId");

                    b.ToTable("ProductBookings");
                });

            modelBuilder.Entity("Dive_Deep.Models.BCD", b =>
                {
                    b.HasBaseType("Dive_Deep.Models.Product");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sizes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("BCDs", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Brand = "Scubapro",
                            PricePerDay = 125,
                            Model = "Navigator Lite BCD",
                            Sizes = "S"
                        },
                        new
                        {
                            ProductId = 2,
                            Brand = "Scubapro",
                            PricePerDay = 125,
                            Model = "Navigator Lite BCD",
                            Sizes = "M"
                        },
                        new
                        {
                            ProductId = 3,
                            Brand = "Scubapro",
                            PricePerDay = 125,
                            Model = "Navigator Lite BCD",
                            Sizes = "L"
                        },
                        new
                        {
                            ProductId = 4,
                            Brand = "Scubapro",
                            PricePerDay = 140,
                            Model = "BCD Glide",
                            Sizes = "S"
                        },
                        new
                        {
                            ProductId = 5,
                            Brand = "Scubapro",
                            PricePerDay = 140,
                            Model = "BCD Glide",
                            Sizes = "M"
                        },
                        new
                        {
                            ProductId = 6,
                            Brand = "Scubapro",
                            PricePerDay = 140,
                            Model = "BCD Glide",
                            Sizes = "L"
                        },
                        new
                        {
                            ProductId = 7,
                            Brand = "Scubapro",
                            PricePerDay = 200,
                            Model = "BCD Hydros Pro",
                            Sizes = "S"
                        },
                        new
                        {
                            ProductId = 8,
                            Brand = "Scubapro",
                            PricePerDay = 200,
                            Model = "BCD Hydros Pro",
                            Sizes = "M"
                        },
                        new
                        {
                            ProductId = 9,
                            Brand = "Scubapro",
                            PricePerDay = 200,
                            Model = "BCD Hydros Pro",
                            Sizes = "L"
                        },
                        new
                        {
                            ProductId = 10,
                            Brand = "Seac",
                            PricePerDay = 145,
                            Model = "BCD Modular",
                            Sizes = "S"
                        },
                        new
                        {
                            ProductId = 11,
                            Brand = "Seac",
                            PricePerDay = 145,
                            Model = "BCD Modular",
                            Sizes = "M"
                        },
                        new
                        {
                            ProductId = 12,
                            Brand = "Seac",
                            PricePerDay = 145,
                            Model = "BCD Modular",
                            Sizes = "L"
                        });
                });

            modelBuilder.Entity("Dive_Deep.Models.DivingSuit", b =>
                {
                    b.HasBaseType("Dive_Deep.Models.Product");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sizes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Thickness")
                        .HasColumnType("real");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("DivingSuits", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 13,
                            Brand = "Scubapro",
                            PricePerDay = 100,
                            Gender = "Herre",
                            Model = "Definition",
                            Sizes = "XS",
                            Thickness = 3f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 14,
                            Brand = "Scubapro",
                            PricePerDay = 100,
                            Gender = "Dame",
                            Model = "Definition",
                            Sizes = "XS",
                            Thickness = 3f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 15,
                            Brand = "Scubapro",
                            PricePerDay = 100,
                            Gender = "Herre",
                            Model = "Definition",
                            Sizes = "XS",
                            Thickness = 5f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 16,
                            Brand = "Scubapro",
                            PricePerDay = 100,
                            Gender = "Dame",
                            Model = "Definition",
                            Sizes = "XS",
                            Thickness = 5f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 17,
                            Brand = "Scubapro",
                            PricePerDay = 100,
                            Gender = "Herre",
                            Model = "Definition",
                            Sizes = "XS",
                            Thickness = 7f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 18,
                            Brand = "Scubapro",
                            PricePerDay = 100,
                            Gender = "Dame",
                            Model = "Definition",
                            Sizes = "XS",
                            Thickness = 7f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 19,
                            Brand = "Scubapro",
                            PricePerDay = 100,
                            Gender = "Herre",
                            Model = "Definition",
                            Sizes = "S",
                            Thickness = 3f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 20,
                            Brand = "Scubapro",
                            PricePerDay = 100,
                            Gender = "Dame",
                            Model = "Definition",
                            Sizes = "S",
                            Thickness = 3f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 21,
                            Brand = "Scubapro",
                            PricePerDay = 100,
                            Gender = "Herre",
                            Model = "Definition",
                            Sizes = "S",
                            Thickness = 5f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 22,
                            Brand = "Scubapro",
                            PricePerDay = 100,
                            Gender = "Dame",
                            Model = "Definition",
                            Sizes = "S",
                            Thickness = 5f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 23,
                            Brand = "Scubapro",
                            PricePerDay = 100,
                            Gender = "Herre",
                            Model = "Definition",
                            Sizes = "S",
                            Thickness = 7f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 24,
                            Brand = "Scubapro",
                            PricePerDay = 100,
                            Gender = "Dame",
                            Model = "Definition",
                            Sizes = "S",
                            Thickness = 7f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 25,
                            Brand = "Scubapro",
                            PricePerDay = 100,
                            Gender = "Herre",
                            Model = "Definition",
                            Sizes = "M",
                            Thickness = 3f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 26,
                            Brand = "Scubapro",
                            PricePerDay = 100,
                            Gender = "Dame",
                            Model = "Definition",
                            Sizes = "M",
                            Thickness = 3f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 27,
                            Brand = "Scubapro",
                            PricePerDay = 100,
                            Gender = "Herre",
                            Model = "Definition",
                            Sizes = "M",
                            Thickness = 5f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 28,
                            Brand = "Scubapro",
                            PricePerDay = 100,
                            Gender = "Dame",
                            Model = "Definition",
                            Sizes = "M",
                            Thickness = 5f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 29,
                            Brand = "Scubapro",
                            PricePerDay = 100,
                            Gender = "Herre",
                            Model = "Definition",
                            Sizes = "M",
                            Thickness = 7f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 30,
                            Brand = "Scubapro",
                            PricePerDay = 100,
                            Gender = "Dame",
                            Model = "Definition",
                            Sizes = "M",
                            Thickness = 7f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 31,
                            Brand = "Scubapro",
                            PricePerDay = 100,
                            Gender = "Herre",
                            Model = "Definition",
                            Sizes = "L",
                            Thickness = 3f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 32,
                            Brand = "Scubapro",
                            PricePerDay = 100,
                            Gender = "Dame",
                            Model = "Definition",
                            Sizes = "L",
                            Thickness = 3f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 33,
                            Brand = "Scubapro",
                            PricePerDay = 100,
                            Gender = "Herre",
                            Model = "Definition",
                            Sizes = "L",
                            Thickness = 5f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 34,
                            Brand = "Scubapro",
                            PricePerDay = 100,
                            Gender = "Dame",
                            Model = "Definition",
                            Sizes = "L",
                            Thickness = 5f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 35,
                            Brand = "Scubapro",
                            PricePerDay = 100,
                            Gender = "Herre",
                            Model = "Definition",
                            Sizes = "L",
                            Thickness = 7f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 36,
                            Brand = "Scubapro",
                            PricePerDay = 100,
                            Gender = "Dame",
                            Model = "Definition",
                            Sizes = "L",
                            Thickness = 7f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 37,
                            Brand = "Scubapro",
                            PricePerDay = 100,
                            Gender = "Herre",
                            Model = "Definition",
                            Sizes = "XL",
                            Thickness = 3f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 38,
                            Brand = "Scubapro",
                            PricePerDay = 100,
                            Gender = "Dame",
                            Model = "Definition",
                            Sizes = "XL",
                            Thickness = 3f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 39,
                            Brand = "Scubapro",
                            PricePerDay = 100,
                            Gender = "Herre",
                            Model = "Definition",
                            Sizes = "XL",
                            Thickness = 5f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 40,
                            Brand = "Scubapro",
                            PricePerDay = 100,
                            Gender = "Dame",
                            Model = "Definition",
                            Sizes = "XL",
                            Thickness = 5f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 41,
                            Brand = "Scubapro",
                            PricePerDay = 100,
                            Gender = "Herre",
                            Model = "Definition",
                            Sizes = "XL",
                            Thickness = 7f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 42,
                            Brand = "Scubapro",
                            PricePerDay = 100,
                            Gender = "Dame",
                            Model = "Definition",
                            Sizes = "XL",
                            Thickness = 7f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 43,
                            Brand = "Waterproof",
                            PricePerDay = 100,
                            Gender = "Herre",
                            Model = "W5",
                            Sizes = "XS",
                            Thickness = 3.5f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 44,
                            Brand = "Waterproof",
                            PricePerDay = 100,
                            Gender = "Dame",
                            Model = "W5",
                            Sizes = "XS",
                            Thickness = 3.5f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 45,
                            Brand = "Waterproof",
                            PricePerDay = 100,
                            Gender = "Herre",
                            Model = "W5",
                            Sizes = "S",
                            Thickness = 3.5f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 46,
                            Brand = "Waterproof",
                            PricePerDay = 100,
                            Gender = "Dame",
                            Model = "W5",
                            Sizes = "S",
                            Thickness = 3.5f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 47,
                            Brand = "Waterproof",
                            PricePerDay = 100,
                            Gender = "Herre",
                            Model = "W5",
                            Sizes = "M",
                            Thickness = 3.5f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 48,
                            Brand = "Waterproof",
                            PricePerDay = 100,
                            Gender = "Dame",
                            Model = "W5",
                            Sizes = "M",
                            Thickness = 3.5f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 49,
                            Brand = "Waterproof",
                            PricePerDay = 100,
                            Gender = "Herre",
                            Model = "W5",
                            Sizes = "L",
                            Thickness = 3.5f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 50,
                            Brand = "Waterproof",
                            PricePerDay = 100,
                            Gender = "Dame",
                            Model = "W5",
                            Sizes = "L",
                            Thickness = 3.5f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 51,
                            Brand = "Waterproof",
                            PricePerDay = 100,
                            Gender = "Herre",
                            Model = "W5",
                            Sizes = "XL",
                            Thickness = 3.5f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 52,
                            Brand = "Waterproof",
                            PricePerDay = 100,
                            Gender = "Dame",
                            Model = "W5",
                            Sizes = "XL",
                            Thickness = 3.5f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 53,
                            Brand = "Fourth Element",
                            PricePerDay = 120,
                            Gender = "Herre",
                            Model = "Proteus",
                            Sizes = "XS",
                            Thickness = 5f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 54,
                            Brand = "Fourth Element",
                            PricePerDay = 120,
                            Gender = "Dame",
                            Model = "Proteus",
                            Sizes = "XS",
                            Thickness = 5f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 55,
                            Brand = "Fourth Element",
                            PricePerDay = 120,
                            Gender = "Herre",
                            Model = "Proteus",
                            Sizes = "S",
                            Thickness = 5f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 56,
                            Brand = "Fourth Element",
                            PricePerDay = 120,
                            Gender = "Dame",
                            Model = "Proteus",
                            Sizes = "S",
                            Thickness = 5f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 57,
                            Brand = "Fourth Element",
                            PricePerDay = 120,
                            Gender = "Herre",
                            Model = "Proteus",
                            Sizes = "M",
                            Thickness = 5f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 58,
                            Brand = "Fourth Element",
                            PricePerDay = 120,
                            Gender = "Dame",
                            Model = "Proteus",
                            Sizes = "M",
                            Thickness = 5f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 59,
                            Brand = "Fourth Element",
                            PricePerDay = 120,
                            Gender = "Herre",
                            Model = "Proteus",
                            Sizes = "L",
                            Thickness = 5f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 60,
                            Brand = "Fourth Element",
                            PricePerDay = 120,
                            Gender = "Dame",
                            Model = "Proteus",
                            Sizes = "L",
                            Thickness = 5f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 61,
                            Brand = "Fourth Element",
                            PricePerDay = 120,
                            Gender = "Herre",
                            Model = "Proteus",
                            Sizes = "XL",
                            Thickness = 5f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 62,
                            Brand = "Fourth Element",
                            PricePerDay = 120,
                            Gender = "Dame",
                            Model = "Proteus",
                            Sizes = "XL",
                            Thickness = 5f,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 63,
                            Brand = "Scubapro",
                            PricePerDay = 300,
                            Gender = "Herre",
                            Model = "Exodry 4.0",
                            Sizes = "XS",
                            Type = "Tordragt"
                        },
                        new
                        {
                            ProductId = 64,
                            Brand = "Scubapro",
                            PricePerDay = 300,
                            Gender = "Dame",
                            Model = "Exodry 4.0",
                            Sizes = "XS",
                            Type = "Tordragt"
                        },
                        new
                        {
                            ProductId = 65,
                            Brand = "Scubapro",
                            PricePerDay = 300,
                            Gender = "Herre",
                            Model = "Exodry 4.0",
                            Sizes = "S",
                            Type = "Tordragt"
                        },
                        new
                        {
                            ProductId = 66,
                            Brand = "Scubapro",
                            PricePerDay = 300,
                            Gender = "Dame",
                            Model = "Exodry 4.0",
                            Sizes = "S",
                            Type = "Tordragt"
                        },
                        new
                        {
                            ProductId = 67,
                            Brand = "Scubapro",
                            PricePerDay = 300,
                            Gender = "Herre",
                            Model = "Exodry 4.0",
                            Sizes = "M",
                            Type = "Tordragt"
                        },
                        new
                        {
                            ProductId = 68,
                            Brand = "Scubapro",
                            PricePerDay = 300,
                            Gender = "Dame",
                            Model = "Exodry 4.0",
                            Sizes = "M",
                            Type = "Tordragt"
                        },
                        new
                        {
                            ProductId = 69,
                            Brand = "Scubapro",
                            PricePerDay = 300,
                            Gender = "Herre",
                            Model = "Exodry 4.0",
                            Sizes = "L",
                            Type = "Tordragt"
                        },
                        new
                        {
                            ProductId = 70,
                            Brand = "Scubapro",
                            PricePerDay = 300,
                            Gender = "Dame",
                            Model = "Exodry 4.0",
                            Sizes = "L",
                            Type = "Tordragt"
                        },
                        new
                        {
                            ProductId = 71,
                            Brand = "Scubapro",
                            PricePerDay = 300,
                            Gender = "Herre",
                            Model = "Exodry 4.0",
                            Sizes = "XL",
                            Type = "Tordragt"
                        },
                        new
                        {
                            ProductId = 72,
                            Brand = "Scubapro",
                            PricePerDay = 300,
                            Gender = "Dame",
                            Model = "Exodry 4.0",
                            Sizes = "XL",
                            Type = "Tordragt"
                        },
                        new
                        {
                            ProductId = 73,
                            Brand = "Waterproof",
                            PricePerDay = 320,
                            Gender = "Herre",
                            Model = "D7 Evo",
                            Sizes = "XS",
                            Type = "Tordragt"
                        },
                        new
                        {
                            ProductId = 74,
                            Brand = "Waterproof",
                            PricePerDay = 320,
                            Gender = "Dame",
                            Model = "D7 Evo",
                            Sizes = "XS",
                            Type = "Tordragt"
                        },
                        new
                        {
                            ProductId = 75,
                            Brand = "Waterproof",
                            PricePerDay = 320,
                            Gender = "Herre",
                            Model = "D7 Evo",
                            Sizes = "S",
                            Type = "Tordragt"
                        },
                        new
                        {
                            ProductId = 76,
                            Brand = "Waterproof",
                            PricePerDay = 320,
                            Gender = "Dame",
                            Model = "D7 Evo",
                            Sizes = "S",
                            Type = "Tordragt"
                        },
                        new
                        {
                            ProductId = 77,
                            Brand = "Waterproof",
                            PricePerDay = 320,
                            Gender = "Herre",
                            Model = "D7 Evo",
                            Sizes = "M",
                            Type = "Tordragt"
                        },
                        new
                        {
                            ProductId = 78,
                            Brand = "Waterproof",
                            PricePerDay = 320,
                            Gender = "Dame",
                            Model = "D7 Evo",
                            Sizes = "M",
                            Type = "Tordragt"
                        },
                        new
                        {
                            ProductId = 79,
                            Brand = "Waterproof",
                            PricePerDay = 320,
                            Gender = "Herre",
                            Model = "D7 Evo",
                            Sizes = "L",
                            Type = "Tordragt"
                        },
                        new
                        {
                            ProductId = 80,
                            Brand = "Waterproof",
                            PricePerDay = 320,
                            Gender = "Dame",
                            Model = "D7 Evo",
                            Sizes = "L",
                            Type = "Tordragt"
                        },
                        new
                        {
                            ProductId = 81,
                            Brand = "Waterproof",
                            PricePerDay = 320,
                            Gender = "Herre",
                            Model = "D7 Evo",
                            Sizes = "XL",
                            Type = "Tordragt"
                        },
                        new
                        {
                            ProductId = 82,
                            Brand = "Waterproof",
                            PricePerDay = 320,
                            Gender = "Dame",
                            Model = "D7 Evo",
                            Sizes = "XL",
                            Type = "Tordragt"
                        },
                        new
                        {
                            ProductId = 83,
                            Brand = "Santi",
                            PricePerDay = 350,
                            Gender = "Herre",
                            Model = "E.Lite Plus",
                            Sizes = "XS",
                            Type = "Tordragt"
                        },
                        new
                        {
                            ProductId = 84,
                            Brand = "Santi",
                            PricePerDay = 350,
                            Gender = "Dame",
                            Model = "E.Lite Plus",
                            Sizes = "XS",
                            Type = "Tordragt"
                        },
                        new
                        {
                            ProductId = 85,
                            Brand = "Santi",
                            PricePerDay = 350,
                            Gender = "Herre",
                            Model = "E.Lite Plus",
                            Sizes = "S",
                            Type = "Tordragt"
                        },
                        new
                        {
                            ProductId = 86,
                            Brand = "Santi",
                            PricePerDay = 350,
                            Gender = "Dame",
                            Model = "E.Lite Plus",
                            Sizes = "S",
                            Type = "Tordragt"
                        },
                        new
                        {
                            ProductId = 87,
                            Brand = "Santi",
                            PricePerDay = 350,
                            Gender = "Herre",
                            Model = "E.Lite Plus",
                            Sizes = "M",
                            Type = "Tordragt"
                        },
                        new
                        {
                            ProductId = 88,
                            Brand = "Santi",
                            PricePerDay = 350,
                            Gender = "Dame",
                            Model = "E.Lite Plus",
                            Sizes = "M",
                            Type = "Tordragt"
                        },
                        new
                        {
                            ProductId = 89,
                            Brand = "Santi",
                            PricePerDay = 350,
                            Gender = "Herre",
                            Model = "E.Lite Plus",
                            Sizes = "L",
                            Type = "Tordragt"
                        },
                        new
                        {
                            ProductId = 90,
                            Brand = "Santi",
                            PricePerDay = 350,
                            Gender = "Dame",
                            Model = "E.Lite Plus",
                            Sizes = "L",
                            Type = "Tordragt"
                        },
                        new
                        {
                            ProductId = 91,
                            Brand = "Santi",
                            PricePerDay = 350,
                            Gender = "Herre",
                            Model = "E.Lite Plus",
                            Sizes = "XL",
                            Type = "Tordragt"
                        },
                        new
                        {
                            ProductId = 92,
                            Brand = "Santi",
                            PricePerDay = 350,
                            Gender = "Dame",
                            Model = "E.Lite Plus",
                            Sizes = "XL",
                            Type = "Tordragt"
                        });
                });

            modelBuilder.Entity("Dive_Deep.Models.Finns", b =>
                {
                    b.HasBaseType("Dive_Deep.Models.Product");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sizes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Finns", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 107,
                            Brand = "Scubapro",
                            PricePerDay = 50,
                            Model = "Jet Fin",
                            Sizes = "XS"
                        },
                        new
                        {
                            ProductId = 108,
                            Brand = "Scubapro",
                            PricePerDay = 50,
                            Model = "Jet Fin",
                            Sizes = "S"
                        },
                        new
                        {
                            ProductId = 109,
                            Brand = "Scubapro",
                            PricePerDay = 50,
                            Model = "Jet Fin",
                            Sizes = "M"
                        },
                        new
                        {
                            ProductId = 110,
                            Brand = "Scubapro",
                            PricePerDay = 50,
                            Model = "Jet Fin",
                            Sizes = "L"
                        },
                        new
                        {
                            ProductId = 111,
                            Brand = "Scubapro",
                            PricePerDay = 50,
                            Model = "Jet Fin",
                            Sizes = "XL"
                        },
                        new
                        {
                            ProductId = 112,
                            Brand = "Scubapro",
                            PricePerDay = 50,
                            Model = "GO Travel",
                            Sizes = "XS"
                        },
                        new
                        {
                            ProductId = 113,
                            Brand = "Scubapro",
                            PricePerDay = 50,
                            Model = "GO Travel",
                            Sizes = "S"
                        },
                        new
                        {
                            ProductId = 114,
                            Brand = "Scubapro",
                            PricePerDay = 50,
                            Model = "GO Travel",
                            Sizes = "M"
                        },
                        new
                        {
                            ProductId = 115,
                            Brand = "Scubapro",
                            PricePerDay = 50,
                            Model = "GO Travel",
                            Sizes = "L"
                        },
                        new
                        {
                            ProductId = 116,
                            Brand = "Scubapro",
                            PricePerDay = 50,
                            Model = "GO Travel",
                            Sizes = "XL"
                        },
                        new
                        {
                            ProductId = 117,
                            Brand = "Scubapro",
                            PricePerDay = 60,
                            Model = "Seawing Supernova",
                            Sizes = "XS"
                        },
                        new
                        {
                            ProductId = 118,
                            Brand = "Scubapro",
                            PricePerDay = 60,
                            Model = "Seawing Supernova",
                            Sizes = "S"
                        },
                        new
                        {
                            ProductId = 119,
                            Brand = "Scubapro",
                            PricePerDay = 60,
                            Model = "Seawing Supernova",
                            Sizes = "M"
                        },
                        new
                        {
                            ProductId = 120,
                            Brand = "Scubapro",
                            PricePerDay = 60,
                            Model = "Seawing Supernova",
                            Sizes = "L"
                        },
                        new
                        {
                            ProductId = 121,
                            Brand = "Scubapro",
                            PricePerDay = 60,
                            Model = "Seawing Supernova",
                            Sizes = "XL"
                        },
                        new
                        {
                            ProductId = 122,
                            Brand = "Seac",
                            PricePerDay = 50,
                            Model = "Propulsion",
                            Sizes = "XS"
                        },
                        new
                        {
                            ProductId = 123,
                            Brand = "Seac",
                            PricePerDay = 50,
                            Model = "Propulsion",
                            Sizes = "S"
                        },
                        new
                        {
                            ProductId = 124,
                            Brand = "Seac",
                            PricePerDay = 50,
                            Model = "Propulsion",
                            Sizes = "M"
                        },
                        new
                        {
                            ProductId = 125,
                            Brand = "Seac",
                            PricePerDay = 50,
                            Model = "Propulsion",
                            Sizes = "L"
                        },
                        new
                        {
                            ProductId = 126,
                            Brand = "Seac",
                            PricePerDay = 50,
                            Model = "Propulsion",
                            Sizes = "XL"
                        },
                        new
                        {
                            ProductId = 127,
                            Brand = "Seac",
                            PricePerDay = 50,
                            Model = "ALA",
                            Sizes = "XS"
                        },
                        new
                        {
                            ProductId = 128,
                            Brand = "Seac",
                            PricePerDay = 50,
                            Model = "ALA",
                            Sizes = "S"
                        },
                        new
                        {
                            ProductId = 129,
                            Brand = "Seac",
                            PricePerDay = 50,
                            Model = "ALA",
                            Sizes = "M"
                        },
                        new
                        {
                            ProductId = 130,
                            Brand = "Seac",
                            PricePerDay = 50,
                            Model = "ALA",
                            Sizes = "L"
                        },
                        new
                        {
                            ProductId = 131,
                            Brand = "Seac",
                            PricePerDay = 50,
                            Model = "ALA",
                            Sizes = "XL"
                        },
                        new
                        {
                            ProductId = 132,
                            Brand = "Fourth Element",
                            PricePerDay = 75,
                            Model = "Tech",
                            Sizes = "XS"
                        },
                        new
                        {
                            ProductId = 133,
                            Brand = "Fourth Element",
                            PricePerDay = 75,
                            Model = "Tech",
                            Sizes = "S"
                        },
                        new
                        {
                            ProductId = 134,
                            Brand = "Fourth Element",
                            PricePerDay = 75,
                            Model = "Tech",
                            Sizes = "M"
                        },
                        new
                        {
                            ProductId = 135,
                            Brand = "Fourth Element",
                            PricePerDay = 75,
                            Model = "Tech",
                            Sizes = "L"
                        },
                        new
                        {
                            ProductId = 136,
                            Brand = "Fourth Element",
                            PricePerDay = 75,
                            Model = "Tech",
                            Sizes = "XL"
                        },
                        new
                        {
                            ProductId = 137,
                            Brand = "Fourth Element",
                            PricePerDay = 80,
                            Model = "Rec Fin",
                            Sizes = "XS"
                        },
                        new
                        {
                            ProductId = 138,
                            Brand = "Fourth Element",
                            PricePerDay = 80,
                            Model = "Rec Fin",
                            Sizes = "S"
                        },
                        new
                        {
                            ProductId = 139,
                            Brand = "Fourth Element",
                            PricePerDay = 80,
                            Model = "Rec Fin",
                            Sizes = "M"
                        },
                        new
                        {
                            ProductId = 140,
                            Brand = "Fourth Element",
                            PricePerDay = 80,
                            Model = "Rec Fin",
                            Sizes = "L"
                        },
                        new
                        {
                            ProductId = 141,
                            Brand = "Fourth Element",
                            PricePerDay = 80,
                            Model = "Rec Fin",
                            Sizes = "XL"
                        });
                });

            modelBuilder.Entity("Dive_Deep.Models.MaskSnorkel", b =>
                {
                    b.HasBaseType("Dive_Deep.Models.Product");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("MaskSnorkels", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 100,
                            Brand = "Scubapro",
                            PricePerDay = 50,
                            Model = "Ghost"
                        },
                        new
                        {
                            ProductId = 101,
                            Brand = "Scubapro",
                            PricePerDay = 60,
                            Model = "D-Mask"
                        },
                        new
                        {
                            ProductId = 102,
                            Brand = "Scubapro",
                            PricePerDay = 50,
                            Model = "Spectra Mini"
                        },
                        new
                        {
                            ProductId = 103,
                            Brand = "Scubapro",
                            PricePerDay = 75,
                            Model = "Crystal VU"
                        },
                        new
                        {
                            ProductId = 104,
                            Brand = "Fourth Element",
                            PricePerDay = 75,
                            Model = "Scout Kontrast"
                        },
                        new
                        {
                            ProductId = 105,
                            Brand = "Fourth Element",
                            PricePerDay = 75,
                            Model = "Scout Enhance"
                        },
                        new
                        {
                            ProductId = 106,
                            Brand = "Tusa",
                            PricePerDay = 75,
                            Model = "Element"
                        });
                });

            modelBuilder.Entity("Dive_Deep.Models.RegulatorSet", b =>
                {
                    b.HasBaseType("Dive_Deep.Models.Product");

                    b.Property<string>("FirstStep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Octopus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondStep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("RegulatorSets", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 97,
                            Brand = "Scubapro",
                            PricePerDay = 125,
                            FirstStep = "MK25EVO",
                            Octopus = "R105",
                            SecondStep = "S600"
                        },
                        new
                        {
                            ProductId = 98,
                            Brand = "Scubapro",
                            PricePerDay = 100,
                            FirstStep = "MK17EVO",
                            Octopus = "R095",
                            SecondStep = "C370"
                        },
                        new
                        {
                            ProductId = 99,
                            Brand = "Scubapro",
                            PricePerDay = 150,
                            FirstStep = "MK25EVO BT",
                            Octopus = "S270",
                            SecondStep = "A700 Carbon BT"
                        });
                });

            modelBuilder.Entity("Dive_Deep.Models.Tank", b =>
                {
                    b.HasBaseType("Dive_Deep.Models.Product");

                    b.Property<int>("Volume")
                        .HasColumnType("int");

                    b.ToTable("Tanks", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 93,
                            Brand = "Scubapro",
                            PricePerDay = 150,
                            Volume = 5
                        },
                        new
                        {
                            ProductId = 94,
                            Brand = "Scubapro",
                            PricePerDay = 160,
                            Volume = 10
                        },
                        new
                        {
                            ProductId = 95,
                            Brand = "Scubapro",
                            PricePerDay = 170,
                            Volume = 12
                        },
                        new
                        {
                            ProductId = 96,
                            Brand = "Scubapro",
                            PricePerDay = 180,
                            Volume = 15
                        });
                });

            modelBuilder.Entity("Dive_Deep.Models.ProductBooking", b =>
                {
                    b.HasOne("Dive_Deep.Models.Booking", "Booking")
                        .WithMany("ProductBookings")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dive_Deep.Models.Product", "Product")
                        .WithMany("ProductBookings")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Dive_Deep.Models.BCD", b =>
                {
                    b.HasOne("Dive_Deep.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("Dive_Deep.Models.BCD", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dive_Deep.Models.DivingSuit", b =>
                {
                    b.HasOne("Dive_Deep.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("Dive_Deep.Models.DivingSuit", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dive_Deep.Models.Finns", b =>
                {
                    b.HasOne("Dive_Deep.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("Dive_Deep.Models.Finns", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dive_Deep.Models.MaskSnorkel", b =>
                {
                    b.HasOne("Dive_Deep.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("Dive_Deep.Models.MaskSnorkel", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dive_Deep.Models.RegulatorSet", b =>
                {
                    b.HasOne("Dive_Deep.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("Dive_Deep.Models.RegulatorSet", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dive_Deep.Models.Tank", b =>
                {
                    b.HasOne("Dive_Deep.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("Dive_Deep.Models.Tank", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dive_Deep.Models.Booking", b =>
                {
                    b.Navigation("ProductBookings");
                });

            modelBuilder.Entity("Dive_Deep.Models.Product", b =>
                {
                    b.Navigation("ProductBookings");
                });
#pragma warning restore 612, 618
        }
    }
}
